[project]
name = "dekpkglock"
version = "0.1.18"
description = ""
authors = [
    { name = "sanzenwin", email = "sanzenwin@gmail.com" },
]
dependencies = [
    "toml<=0.10.2",
    "dektools<1.0.0",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.scripts]
dekpkglock = "dekpkglock.click.__entry__:main"

[tool.pdm.build]
includes = [
    "dekpkglock",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
