[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hsr1"
version = "1.0.5"

dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scipy",
    "lmfit",
    "ephem",
    "pvlib",
    "importlib_resources"
]

[project.optional-dependencies]
sg2 = ["sg2"]

[tool.setuptools.package-data]
"*" = ["*.txt"]

[tool.setuptools]
packages = ["hsr1", "hsr1.db", "hsr1.read_txt", "hsr1.utils", "hsr1.utils.spectrum", "hsr1.plots", "hsr1.data", "hsr1.synthetic_dataset"]