[tool.poetry]
name = "omnata-plugin-runtime"
version = "0.4.10"
description = "Classes and common runtime components for building and running Omnata Plugins"
authors = ["James Weakley <james.weakley@omnata.com>"]
readme = "README.md"
packages = [{include = "omnata_plugin_runtime", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
snowflake-snowpark-python = "^1"
# had to relax some of these thanks to snowcli pinning newer versions
certifi	= "<=2023.11.17" # latest version available on Snowflake Anaconda
charset-normalizer = "<=2.0.4" # latest version available on Snowflake Anaconda
idna = "<=3.4" # latest version available on Snowflake Anaconda
jinja2 = ">=3.1.2" # 3.1.2 was latest version available on Snowflake Anaconda
markupsafe = "<=2.1.3" # latest version available on Snowflake Anaconda
numpy = "<=1.26.3" # latest version available on Snowflake Anaconda
packaging = "<=23.1" # latest version available on Snowflake Anaconda
pandas = "<=2.1.4" # latest version available on Snowflake Anaconda
platformdirs = "<=3.10.0" # latest version available on Snowflake Anaconda
pydantic = "^1, <=1.10.12" # latest version available on Snowflake Anaconda
pyjwt = "<=2.4.0" # latest version available on Snowflake Anaconda
pyopenssl = "<=23.2.0" # latest version available on Snowflake Anaconda
pytz = "<=2023.3.post1" # latest version available on Snowflake Anaconda
requests = "^2, <=2.31.0" # latest version available on Snowflake Anaconda
setuptools = ">=68.2.2" # 68.2.2 was latest version available on Snowflake Anaconda
tomlkit = ">=0.11.1" # 0.11.1 was latest version available on Snowflake Anaconda
tenacity = "^8, <=8.2.2" # latest version available on Snowflake Anaconda
urllib3 = "<=2.1.0" # latest version available on Snowflake Anaconda
wheel = "<=0.41.2" # latest version available on Snowflake Anaconda

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
deepdiff = "^6"
requests-mock = ">=1.9.3"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
