[tool.poetry]
name = "pacmanupgradelist"
version = "1.0.0"
description = "List the latest pacman upgrades and show them in a nice table"
authors = ["Marnix Enthoven <mail@marnixenthoven.nl>"]
repository = "https://github.com/narbux/pacmanupgradelist"
readme = "README.md"
license = "GPL-3.0-or-later"
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.9",
    "Topic :: Utilities",
]

[tool.poetry.scripts]
pacmanupgradelist = "pacmanupgradelist.cli:main"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
