[tool.poetry]
name = "dialtone"
version = "0.0.33"
description = "Dialtone"
authors = ["Petr Gazarov <petr@anneal.ai>", "Akash Kashyap <akash@anneal.ai>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.7.4"
requests = "^2.32.3"
httpx = "^0.27.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
toml = "^0.10.2"
wheel = "^0.43.0"
pytest-asyncio = "^0.23.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
