[tool.poetry]
name = "lutzpocflux"
version = "0.1.3"
description = "Calculate POC Export flux, as Lutz et al. 2007"
authors = ["Alex Webber <alexpwebber@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "1.26.4"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


