[project]
name = "pygcloud"
version = "0.0.71"
authors = [
  { name="Jean-Lou Dupont", email="jld@jldupont.com" },
]
description = "Python helper around gcloud"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Repository = "https://github.com/jldupont/pygcloud"
Pypi = "https://pypi.org/project/pygcloud/"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.entry-points."pygcloud.events"]
start_deploy = "pygcloud.events:dummy"
end_deploy = "pygcloud.events:dummy"
before_deploy = "pygcloud.events:dummy"
after_deploy = "pygcloud.events:dummy"
