[project]
name = "legion-cli"
version = "0.3.2"
description = "Commandline Utilities for the Legion Alerting and Monitoring System"
authors = [
    { name = "Eugene Kovalev", email = "eugene@kovalev.systems" },
]
dependencies = [
    "click>=8.0",
    "legion-utils>=0.3.3",
    "rich>=10.8.0",
    "termcolor>=1.1",
]
requires-python = "<4.0,>3.9.0"
readme = "README.md"

[project.license]
text = "GPL-3.0-or-later"

[project.scripts]
legion = "legion_cli.cli:cli"

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.3.0",
    "pytest-cov>=4.0.0",
    "pylint<4.0.0,>=3.2.0",
    "pytest-mock>=3.6.1",
    "mypy<2.0,>=1.0",
    "flake8<8.0.0,>=7.0.0",
    "testcontainers[rabbitmq]>=3.7.1",
    "robotnikmq @ file:///${PROJECT_ROOT}/../robotnikmq",
    "legion-utils @ file:///${PROJECT_ROOT}/../legion-utils",
    "twine>=5.1.1",
]

[tool.pdm.scripts.publish-test]
cmd = "twine upload -r testpypi dist/*"

[tool.pdm.scripts.publish-prod]
cmd = "twine upload -r pypi dist/*"

[tool.pdm.build]
includes = []

[build-system]
requires = [
    "pdm-pep517>=1.0.4",
]
build-backend = "pdm.pep517.api"
