[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "metadata_validator"
version = "0.1.3"
description = "A package designed to put a spreadsheet of a brain imagery dataset into a series of required metadata and validation for data within cells."
readme = "README.md"
authors = [{ name = "Keaton Hutchinson", email = "keatonhutchinson03@gmail.com" }]
keywords = ["python", "bil"]
dependencies = [
    "pandas",
    "openpyxl",
    "requests",
    "beautifulsoup4"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Education",
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]

