[build-system]
requires = [
    "setuptools>=61.0",
    "pathlib",
    "requests",
    "datetime",
    "numpy",
    "matplotlib",
    "pandas",
    "cartopy",
    "netCDF4" ]
build-backend = "setuptools.build_meta"


[project]
name = "oneargopy"
version = "0.1.2"
authors = [
  { name="Savannah Stephenson", email="stephensonsavannah@ymail.com" },
  { name="Hartmut Frenzel", email="hartmut.frenzel@noaa.gov" },
]
description = "An alpha version of oneargopy."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]


[project.urls]
Homepage = "https://github.com/NOAA-PMEL/OneArgoPy"
Issues = "https://github.com/NOAA-PMEL/OneArgoPy/issues"
