[tool.poetry]
name = "grvtree"
version = "0.2.0"
description = "An implementation of Gómez-Rodríguez and Vilares' tree linearization"
homepage = "https://pypi.org/project/grvtree/"
repository = "https://github.com/aslemen/GRV-tree"
authors = ["Nori Hayashi <net@hayashi-lin.net>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
nltk = "^3.8.1"
more-itertools = "^10.2.0"
nltk-tree-extensions = "^3.7.0.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
