[project]
name = "rwhealth-dsptools"
version = "0.1.2"
description = "A set of commonly used ETL functions"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3"
]
dependencies = [
    "azure-storage-blob==12.8.1",
    "paramiko==3.3.1",
    "pymsteams==0.2.2",
    "PyYAML==6.0.1",
    "setuptools==68.2.2",
    "SQLAlchemy>1.4,<2.0.31",
    "pyodbc>=5.0.0",
    "msal==1.30.0"
]

[project.optional-dependencies]
testing = [
    "pytest>=7.4.2",
    "pytest-cov>=4.10",
    "tox>=4.6",
    "pytest-mock==3.14.0"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
