[build-system]
requires = [
    "hatchling>=1.22.2"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_core"
version = "1.4.3"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (core modules)"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "Flask>=3.0.2",
    "pip>=24.0",
    "python-dateutil>=2.8.2",
    "pytz>=2023.3",
    "requests>=2.31.0",
    "setuptools>=68.0.0",
    "wheel>=0.42.0",
    "xmltodict3>=0.0.4"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-Core"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-Core/issues"
