[build-system]
requires = [
    "hatchling>=1.22.2"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_s3"
version = "0.5.4"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (S3 storage modules)"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "pip>=24.0",
    "pypomes_core>=1.4.5",
    "pypomes_http>=0.2.7",
    "setuptools>=68.0.0",
    "Unidecode>=1.3.6",
    "wheel>=0.42.0"
#   "boto3>=1.34.150"
#   "minio>=7.2.7"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-S3"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-S3/issues"
