[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "pyisg"
version = "0.1.0"
authors = [
    { name = "Kentaro Tatsumi", email = "paqira.2019@gmail.com" },
]
description = "Library reading/writing the ISG 2.0 format"
readme = "README.md"
requires-python = ">=3.8"
keywords = [
    "GIS",
    "ISG",
    "isg file",
]
license = { text = "MIT OR Apache-2.0" }
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: GIS",
]

[project.urls]
Documentation = "https://pyisg.readthedocs.io"
Issues = "https://github.com/paqira/pyisg/issues"
Source = "https://github.com/paqira/pyisg"

[tool.maturin]
features = ["pyo3/extension-module"]


# ruff

[tool.ruff]
line-length = 120
exclude = [
    "tests",
    "doc",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "C90",
    "I",
    "N",
    "B",
    "D",
]
ignore = [
    "N999", # Invalid module name:
    "D104", #  Missing docstring in public package
    "D105", # Missing docstring in magic method
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
required-imports = [
    "from __future__ import annotations",
]
