[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Pypable"
version = "0.2.0"
authors = [
  { name="Faelin", email="faelin.codes@gmail.com" },
]
description = "A toolset for piping values between functions, with optional shell-like text-processing tools."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/faelin/Pypable"
Issues = "https://github.com/faelin/Pypable/issues"