[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "processpdfdocs"
version = "0.0.12.11"
authors = [
  { name="Chien Luong Minh", email="chien.lm15@gmail.com" },
]
description = "Extract text and information from pdf files"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "vietocr==0.3.13",
    "opencv-contrib-python==4.6.0.66",
    "PyMuPDF==1.20.2",
    "pdf2image==1.17.0",
    # "pdftotext==2.2.2",
    "PyPDF2==3.0.1",
    "pdfminer.six==20221105",
    "pdfplumber==0.10.2",
    "numpy==1.26.4",
    "pillow==10.2.0",
    "ultralytics==8.0.239",
    "onnxruntime",
    "paddleocr==2.7.0.3",
    "paddlepaddle==2.5.2",
    "openai==1.12.0",
    "pytesseract==0.3.10",
    "Werkzeug==3.0.3"
]