[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[project]
name = "plotlyshare"
version = "1.0.9"
authors = [{name="plutonium239", email="plutonium.239.811@gmail.com"}]
description = "Link-based sharing of `plotly` plots with a private web app"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
	"rich",
	"plotly",
	"wonderwords",
	"requests"
]
keywords = ["plotly", "interactive", "plot"]

[project.urls]
Homepage = "https://github.com/plutonium-239/plotlyshare"
Issues = "https://github.com/plutonium-239/plotlyshare/issues"

[tool.flit.sdist]
exclude = ["*/config.json"]