[project]
name = "hhttpcode"
version = "1.0.1"
authors = [{ name = "hamolicious", email = "hamolicious@hamolicious.net" }]
description = "Quickly look up HTTP codes in the terminal"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "colorama==0.4.6",
    "fire==0.5.0",
    "six==1.16.0",
    "termcolor==2.4.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/httpcode/"]
