[tool.poetry]
name = "clandestino_qdrant"
version = "0.1.0"
description = "Clandestino Qdrant implementation"
authors = ["XimitGaia <im.ximit@gmail.com>"]
readme = "README.md"
packages = [
    {include = "clandestino_qdrant"},
]

[tool.poetry.dependencies]
python = "^3.11"
python-decouple = "^3.8"
qdrant-client = "^1.10.1"
clandestino-interfaces = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
