[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "novus-pytils"
version = "0.0.13"
authors = [
  { name="John McMeen", email="johnmcmeen@gmail.com" },
]
description = "A repository for useful python methods which abstract methods I can never remember how to use."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
  "numpy",
  "opencv-python",
  "scikit-image"
]

[project.optional-dependencies]
keras = [
    "tensorflow[and-cuda]==2.15.*"
]


[project.urls]
Homepage = "https://github.com/jmcmeen/novus-pytils"
