[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "marearts-anpr-d"
version = "0.1.52"
authors = [
    {name = "marearts", email = "hello@marearts.com"},
]
description = "marearts anpr detector"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["numpy"]
dynamic = ["scripts", "optional-dependencies"]

[project.urls]
"Homepage" = "https://github.com/yourusername/marearts-anpr-d"
"Bug Tracker" = "https://github.com/yourusername/marearts-anpr-d/issues"

[tool.setuptools_scm]
write_to = "marearts_anpr/_version.py"
