[tool.poetry]
name = "mypackage202407221751"
version = "0.1.5"
description = ""
authors = ["Jongsoo Kim <jongsoo.kim@theragenbio.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
